### ISSUE TITLE
using mcBV via z3 c++ API

### ISSUE THREAD

**Issue by mm95** [Microsoft/mcBV#2]
Hi,

Is there any way to use mcbv as a static library and join it with my c++ implementation?
or now is there any option to access the capabilities of mcbv from z3 c++ api?
 
thanks so much.

**Comment by wintersteiger** [comment]
Sorry, no, there is currently no way to use mcBV via Z3. mcBV uses Z3's parser and simplifier (so it depends on libz3.dll), but the two tools are not otherwise integrated.

**Comment by mm95** [comment]
Thanks so much for your quick answer. And is there any way to have .a or .so or .la from mcBV?

**Comment by wintersteiger** [comment]
Not at this point. There is no public API and mcBV implemented in F#, so the best we can offer is a managed .DLL, but that would also take us some time to implement.

**Comment by mm95** [comment]
Ok. Thanks for your reply.
